alias Disclist
alias Disclist.Craigslist
alias Disclist.Craigslist.Query
alias Disclist.Craigslist.QueryLoader
alias Disclist.Craigslist.QueryScraper
alias Disclist.Craigslist.Result
alias Disclist.Craigslist.ScraperSupervisor
alias Disclist.Repo
import Ecto.Query
